### ISSUE TITLE
SonarCloud

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#258]
- [x] Check if it's free for open source, otherwise chose an alternative
- [ ] Setup (Git Actions).
- [ ] Automatically fail a build if newly introduced bugs / code smells are introduced in a PR

**Comment by Lithrun** [comment]
Currently placing this issue on hold. Whereas SonarCloud integration is there, it doesn't scan C# code if it isn't compiled. This has to be done via a special unity build action, yet that doesn't seem to be working on Unity 2017. Seems to work fine on 2018, 2019 and 2020.

Thereby, placing this issue on hold, unless someone else wants to give it a shot. Problem is that activating an unity 2017 license doesn't appear to be working. Documentation available at: https://unity-ci.com/docs

Build yml:

```name: Actions

on:
  pull_request: {}
  push: { branches: [development] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2017.3.0f1
          targetPlatform: StandaloneWindows64

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
          
  sonarCloudTrigger:
    needs: build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=aottg-2
            -Dsonar.projectKey=AoTTG-2_AoTTG-2
```

**Comment by Lithrun** [comment]
Currently working for Unity 2020 #259 
```
#name: Acquire activation file
#on: [push]
#jobs:
#  activation:
#    name: Request manual activation file 🔑
#    runs-on: ubuntu-latest
#    steps:
#      # Request manual activation file
#      - name: Request manual activation file
#        id: getManualLicenseFile
#        uses: webbertakken/unity-request-manual-activation-file@v1.1
#        with:
#          unityVersion: 2020.1.4f1
#      # Upload artifact (Unity_v20XX.X.XXXX.alf)
#      - name: Expose as artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
#          path: ${{ steps.getManualLicenseFile.outputs.filePath }}

name: CI
on:
  pull_request: {}
  push: { branches: [development] }
  
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:   
  CI:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      #- name: Run tests
      #  uses: webbertakken/unity-test-runner@v1.3
      #  with:
      #    unityVersion: 2020.1.4f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2020.1.4f1
          targetPlatform: StandaloneWindows64
  
      - name: SonarQube analysis
        if: always()
        uses: MirrorNG/unity-runner@3.0.0
        with:
          entrypoint: /sonar-scanner.sh
          projectKey: AoTTG-2_AoTTG-2
          projectName: AoTTG-2
          sonarOrganisation: aottg-2
          beginArguments: /d:sonar.verbose="true"
        env:
          FrameworkPathOverride: /opt/Unity/Editor/Data/MonoBleedingEdge/
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

#  Release:
#    runs-on: ubuntu-latest
#    needs: CI
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
  
#      - name: Release
#        uses: cycjimmy/semantic-release-action@v2
#        with:
#          extra_plugins: |
#            @semantic-release/exec
#            @semantic-release/changelog
#            @semantic-release/git
#          branch: development
#        env:
#          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
```
